config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  get 'welcome/about'
  get 'registers' =>  'welcome#index'

  root to: 'welcome#index'

  end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <ul class="nav nav-tabs">
    <% if current_user %>
    <li><%= link_to "Home", welcome_index_path %></li>
    <li><%= link_to "About", welcome_about_path %></li>
  <% end %>
  <div class="pull-right user-info">
           <% if current_user %>
              <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
                       <span class="sr-only">Sign out</span>
                       <span class="glyphicon glyphicon-log-out"></span>
               <% end %>
           <% else %>     
                        <%= link_to "Sign In", new_user_session_path %> or
                        <%= link_to "Sign Up", new_user_registration_path %>
                
           <% end %>
  </div>
  </ul> 
  </div>
    <% if flash.now[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash.now[:notice] %>
         </div>
   <% elsif flash.now[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash.now[:error] %>
         </div>
   <% elsif flash.now[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash.now[:alert] %>
         </div>
   <% end %>     
</div>

<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<div class="jumbotron">
  <h1>Blocmetrics</h1>
  <p>API Tracking Service and Reporting Tool <br>
  Build an analytics service and reporting tool that you can use with web apps to track user activity and report results. </p>
  <p>
  There are plenty of good analytic services, but that doesn't mean you can't build a better one. This analytics service will offer a few key features:

   - A client-side JavaScript snippet that allows a user to track events on their website.
   - A server-side API that captures and saves those events to a database.
   - A Rails application that displays the captured event data for a user.
  </p>
  <p> Created by: Nithya Rao</p>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Blocmetrics</h1>
  <p>API Tracking Service and Reporting Tool <br>
   Build an analytics service and reporting tool that you can use with web apps to track user activity and report results. </p>
  
</div>